Business Logic/config/routes.rb
BusinessLogic::Application.routes.draw do
  resources :reservations

  resources :moniteurs

  resources :reservations

  resources :users do
	collection do
		post 'test'
	end
  end

   root :to => 'users#index'

end

Business Logic/app/models/moniteur.rb
class Moniteur < ActiveRecord::Base
end

Business Logic/app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

Business Logic/app/models/user.rb
class User < ActiveRecord::Base
end

Business Logic/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Business Logic/app/controllers/moniteurs_controller.rb
class MoniteursController < ApplicationController
  # GET /moniteurs
  # GET /moniteurs.json
  def index
    @moniteurs = Moniteur.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @moniteurs }
    end
  end

  # GET /moniteurs/1
  # GET /moniteurs/1.json
  def show
    @moniteur = Moniteur.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @moniteur }
    end
  end

  # GET /moniteurs/new
  # GET /moniteurs/new.json
  def new
    @moniteur = Moniteur.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @moniteur }
    end
  end

  # GET /moniteurs/1/edit
  def edit
    @moniteur = Moniteur.find(params[:id])
  end

  # POST /moniteurs
  # POST /moniteurs.json
  def create
    @moniteur = Moniteur.new(params[:moniteur])

    respond_to do |format|
      if @moniteur.save
        format.html { redirect_to @moniteur, notice: 'Moniteur was successfully created.' }
        format.json { render json: @moniteur, status: :created, location: @moniteur }
      else
        format.html { render action: "new" }
        format.json { render json: @moniteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /moniteurs/1
  # PUT /moniteurs/1.json
  def update
    @moniteur = Moniteur.find(params[:id])

    respond_to do |format|
      if @moniteur.update_attributes(params[:moniteur])
        format.html { redirect_to @moniteur, notice: 'Moniteur was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @moniteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moniteurs/1
  # DELETE /moniteurs/1.json
  def destroy
    @moniteur = Moniteur.find(params[:id])
    @moniteur.destroy

    respond_to do |format|
      format.html { redirect_to moniteurs_url }
      format.json { head :ok }
    end
  end
end

Business Logic/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :ok }
    end
  end
end

Business Logic/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users } 
      format.xml { render xml: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
      format.xml { render xml: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
      format.xml { render xml: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
        format.xml { render xml: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
        format.xml { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
      format.xml { head :ok }
    end
  end
  
  #Test methode
  def test
	#@test = params[:user]
	@user = User.new(params[:user])
	respond_to do |format|
		format.json {render json: @user}
	end
  end
end

Business Logic/app/helpers/application_helper.rb
module ApplicationHelper
end

Business Logic/app/helpers/moniteurs_helper.rb
module MoniteursHelper
end

Business Logic/app/helpers/reservations_helper.rb
module ReservationsHelper
end

Business Logic/app/helpers/users_helper.rb
module UsersHelper
end

Business Logic/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusinessLogic</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Business Logic/app/views/moniteurs/_form.html.erb
<%= form_for(@moniteur) do |f| %>
  <% if @moniteur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moniteur.errors.count, "error") %> prohibited this moniteur from being saved:</h2>

      <ul>
      <% @moniteur.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Business Logic/app/views/moniteurs/edit.html.erb
<h1>Editing moniteur</h1>

<%= render 'form' %>

<%= link_to 'Show', @moniteur %> |
<%= link_to 'Back', moniteurs_path %>

Business Logic/app/views/moniteurs/index.html.erb
<h1>Listing moniteurs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Lastname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @moniteurs.each do |moniteur| %>
  <tr>
    <td><%= moniteur.name %></td>
    <td><%= moniteur.lastname %></td>
    <td><%= link_to 'Show', moniteur %></td>
    <td><%= link_to 'Edit', edit_moniteur_path(moniteur) %></td>
    <td><%= link_to 'Destroy', moniteur, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Moniteur', new_moniteur_path %>

Business Logic/app/views/moniteurs/new.html.erb
<h1>New moniteur</h1>

<%= render 'form' %>

<%= link_to 'Back', moniteurs_path %>

Business Logic/app/views/moniteurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @moniteur.name %>
</p>

<p>
  <b>Lastname:</b>
  <%= @moniteur.lastname %>
</p>


<%= link_to 'Edit', edit_moniteur_path(@moniteur) %> |
<%= link_to 'Back', moniteurs_path %>

Business Logic/app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idMoniteur %><br />
    <%= f.number_field :idMoniteur %>
  </div>
  <div class="field">
    <%= f.label :IDUser %><br />
    <%= f.number_field :IDUser %>
  </div>
  <div class="field">
    <%= f.label :startDate %><br />
    <%= f.date_select :startDate %>
  </div>
  <div class="field">
    <%= f.label :endDate %><br />
    <%= f.date_select :endDate %>
  </div>
  <div class="field">
    <%= f.label :Language %><br />
    <%= f.text_field :Language %>
  </div>
  <div class="field">
    <%= f.label :payed %><br />
    <%= f.check_box :payed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Business Logic/app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

Business Logic/app/views/reservations/index.html.erb
<h1>Listing reservations</h1>

<table>
  <tr>
    <th>Idmoniteur</th>
    <th>Iduser</th>
    <th>Startdate</th>
    <th>Enddate</th>
    <th>Language</th>
    <th>Payed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reservations.each do |reservation| %>
  <tr>
    <td><%= reservation.idMoniteur %></td>
    <td><%= reservation.IDUser %></td>
    <td><%= reservation.startDate %></td>
    <td><%= reservation.endDate %></td>
    <td><%= reservation.Language %></td>
    <td><%= reservation.payed %></td>
    <td><%= link_to 'Show', reservation %></td>
    <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
    <td><%= link_to 'Destroy', reservation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reservation', new_reservation_path %>

Business Logic/app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

Business Logic/app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Idmoniteur:</b>
  <%= @reservation.idMoniteur %>
</p>

<p>
  <b>Iduser:</b>
  <%= @reservation.IDUser %>
</p>

<p>
  <b>Startdate:</b>
  <%= @reservation.startDate %>
</p>

<p>
  <b>Enddate:</b>
  <%= @reservation.endDate %>
</p>

<p>
  <b>Language:</b>
  <%= @reservation.Language %>
</p>

<p>
  <b>Payed:</b>
  <%= @reservation.payed %>
</p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

Business Logic/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br />
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :adress %><br />
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Business Logic/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Business Logic/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th>Name</th>
    <th>Lastname</th>
    <th>Adress</th>
    <th>Zip</th>
    <th>City</th>
    <th>Country</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= user.name %></td>
    <td><%= user.lastName %></td>
    <td><%= user.adress %></td>
    <td><%= user.zip %></td>
    <td><%= user.city %></td>
    <td><%= user.country %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

Business Logic/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

Business Logic/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Lastname:</b>
  <%= @user.lastName %>
</p>

<p>
  <b>Adress:</b>
  <%= @user.adress %>
</p>

<p>
  <b>Zip:</b>
  <%= @user.zip %>
</p>

<p>
  <b>City:</b>
  <%= @user.city %>
</p>

<p>
  <b>Country:</b>
  <%= @user.country %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>